services:

  mssql:
    image: ${TARGET_REGISTRY}${PROJECT_NAME}-mssql:${VERSION:-latest}
    build:
      context: ./docker/build/external
      args:
        BASE_IMAGE: mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04

  solr:
    image: ${TARGET_REGISTRY}${PROJECT_NAME}-solr:${VERSION:-latest}
    build:
      context: ./docker/build/external
      args:
        BASE_IMAGE: solr:8.8.2
