services:

  redis:
    image: ${TARGET_REGISTRY}${PROJECT_NAME}-redis:${VERSION:-latest}
    build:
      context: ./docker/build/external
      args:
        BASE_IMAGE: redis:4.0.14-alpine

  mssql:
    image: ${TARGET_REGISTRY}${PROJECT_NAME}-mssql:${VERSION:-latest}
    build:
      context: ./docker/build/external
      args:
        BASE_IMAGE: mcr.microsoft.com/mssql/server:2017-CU21-ubuntu-16.04
