apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../sitecore/ltsc2019/xm1/secrets
- ../../sitecore/ltsc2019/xm1/configmaps
- ../../sitecore/ltsc2019/xm1/init
- ../../sitecore/ltsc2019/xm1/volumes/azurefile
- ../../sitecore/ltsc2019/xm1

resources:
- ingress.yaml
- ingress-configuration.yaml
- letsencrypt-issuer.yaml
- rendering.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: custom-hostnames
  files:
  - www-hostname

secretGenerator:
- name: sitecore-id-cli
  files:
  - cli-clientid.txt
  - cli-clientsecret.txt

vars:
- name: www-hostname
  objref:
    kind: ConfigMap
    name: custom-hostnames
    apiVersion: v1
  fieldref:
    fieldpath: data.www-hostname

patches:
  - path: ./patch.cm-rendering.yaml
    target:
      kind: Deployment
      name: cm

  # We use tolerations to actively allow Windows containers and
  # prevent linux containers without nodeSelector to be scheduled on Windows nodes
  - path: ./patch.tolerations.yaml
    target:
      kind: Deployment
  - path: ./patch.tolerations.yaml
    target:
      kind: Job

  # Sitecore CLI
  - path: ./patch.id-cli.yaml
    target:
      kind: Deployment
      name: id
  - path: ./patch.cm-cli.yaml
    target:
      kind: Deployment
      name: id

