apiVersion: v1
kind: Service
metadata:
  name: rendering
spec:
  selector:
    app: rendering
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rendering
  labels:
    app: rendering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rendering
  template:
    metadata:
      labels:
        app: rendering
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: rendering
        image: rendering
        ports:
        - containerPort: 80
        env:
        - name: Sitecore__InstanceUri
          value: https://$(cm-hostname)
        - name: Sitecore__RenderingHostUri
          value: https://$(www-hostname)
        - name: Sitecore__EnableExperienceEditor
          value: 'true'

        livenessProbe:
          httpGet:
            path: /healthz/live
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz/ready
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Startup
          timeoutSeconds: 300
          periodSeconds: 30
          failureThreshold: 10

        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1500m
      imagePullSecrets:
      - name: sitecore-docker-registry