parameters:
- name: project_name
  type: string
- name: version_tag
  type: string
- name: target_docker_registry
  type: string
- name: windows_pool_name
  type: string
  default: Azure Pipelines
- name: windows_pool_vm
  type: string
  default: windows-latest
- name: solution_image_artifact
  type: string
  default: Windows_solution
- name: push_image
  type: string
  default: 'true'

jobs:
- job: build_solution
  displayName: Build solution
  pool:
    name: '${{ parameters.windows_pool_name }}'
    vmImage: '${{ parameters.windows_pool_vm }}'
  steps:
  - checkout: self

  - template: build-steps.yml
    parameters:
      project_name: ${{ variables.project_name }}
      version_tag: $(version_tag)
      target_docker_registry: $(target_docker_registry)
      compose_file: docker-compose.yml
      service_names: solution
      artifact_name: ${{ parameters.solution_image_artifact }}
      push_images: ${{ parameters.push_image }}
